### Exercicio de Fechamento do Conteúdo


Imagine que você foi contratado como analista de dados para uma empresa fictícia chamada DataCorp. A empresa deseja entender melhor os perfis dos funcionários cadastrados em seu sistema, identificar padrões salariais, explorar dados de localização e realizar análises avançadas para tomadas de decisão estratégicas.

A DataCorp já possui um banco de dados em formato CSV, que contém informações como IDs, nomes, idades, salários e as cidades onde os funcionários moram. Sua tarefa será realizar uma série de operações nesse banco, utilizando o pandas, para responder às seguintes perguntas:

- Qual a distribuição de idades e salários no banco de dados?
- Existem valores ausentes? Como podemos tratá-los?
- Quem são os funcionários com salários acima de R$8.000,00?
- Como criar uma nova coluna que categoriza os salários em "Baixa", "Média" e "Alta"?
- Qual a média salarial por cidade?
- Como adicionar novos registros de funcionários ao banco de dados?

In [6]:
import pandas as pd
import numpy as np




# Leitura do banco de dados do arquivo CSV para um DataFrame.
banco = pd.read_csv('banco_ficticio.csv')


# Etapa 1: Ler o banco de dados e descobrir qual a distribuição de idades e salários no banco de dados
print("\nEstatísticas descritivas:")
print(banco.describe())


#Etapa 2:  Existem valores ausentes? Como podemos tratá-los?
#Esse banco de dados é um banco de dados completo, não há valores ausentes



# Etapa 3: Quem são os funcionários com salários acima de R$8.000,00?
salarios_altos = banco[banco['Salário'] > 8000]
print("\nRegistros com salários acima de 8000:")
print(salarios_altos)


#Etapa 4: Como criar uma nova coluna que categoriza os salários em "Baixa", "Média" e "Alta"?
banco['Faixa Salarial'] = pd.cut(banco['Salário'], bins=[2000, 5000, 8000, 10000], labels=['Baixa', 'Média', 'Alta'])
print("\nBanco com nova coluna 'Faixa Salarial':")
print(banco.head())


# Etapa 5: Qual a média salarial por cidade?
media_salario_por_cidade = banco.groupby('Cidade')['Salário'].mean()
print("\nMédia salarial por cidade:")
print(media_salario_por_cidade)

#Etapa 6: Como adicionar novos registros de funcionários ao banco de dados?
novos_dados = pd.DataFrame({
    'ID': [101, 102],
    'Nome': ['Pessoa 101', 'Pessoa 102'],
    'Idade': [45, 29],
    'Salário': [9500, 3000],
    'Cidade': ['Fortaleza', 'Recife']
})

# Expandimos o banco de dados original com os novos registros.
banco_expandido = pd.concat([banco, novos_dados], ignore_index=True)
print("\nBanco expandido com novos registros:")
print(banco_expandido.tail())

Estatísticas descritivas:
               ID       Idade      Salário
count  100.000000  100.000000   100.000000
mean    50.500000   40.610000  6147.920000
std     29.011492   14.839134  2415.333646
min      1.000000   18.000000  2080.000000
25%     25.750000   26.750000  3685.750000
50%     50.500000   41.500000  6305.500000
75%     75.250000   55.000000  8222.000000
max    100.000000   63.000000  9994.000000

Registros com salários acima de 8000:
    ID       Nome  Idade  Salário          Cidade
0    1   Pessoa 1     51     9739       São Paulo
3    4   Pessoa 4     21     9328  Rio de Janeiro
4    5   Pessoa 5     19     8588  Rio de Janeiro
6    7   Pessoa 7     29     8165  Belo Horizonte
7    8   Pessoa 8     22     9588       São Paulo
9   10  Pessoa 10     56     8156  Rio de Janeiro
11  12  Pessoa 12     20     9648        Curitiba
12  13  Pessoa 13     62     8769       São Paulo
15  16  Pessoa 16     22     8531       São Paulo
17  18  Pessoa 18     21     9943       São Paulo
24  25  Pessoa 25     26     9900  Belo Horizonte
25  26  Pessoa 26     18     8745        Curitiba
29  30  Pessoa 30     23     9161  Rio de Janeiro
30  31  Pessoa 31     61     9015        Curitiba
43  44  Pessoa 44     41     8801  Rio de Janeiro
51  52  Pessoa 52     56     9580  Belo Horizonte
52  53  Pessoa 53     42     8086  Rio de Janeiro
53  54  Pessoa 54     28     8482  Rio de Janeiro
56  57  Pessoa 57     28     9994        Curitiba
60  61  Pessoa 61     27     9228  Rio de Janeiro
61  62  Pessoa 62     48     9820        Curitiba
68  69  Pessoa 69     29     9854       São Paulo
74  75  Pessoa 75     44     8086       São Paulo
75  76  Pessoa 76     51     9162       São Paulo
79  80  Pessoa 80     37     8633  Rio de Janeiro
81  82  Pessoa 82     48     9072       São Paulo
88  89  Pessoa 89     24     9460  Rio de Janeiro
90  91  Pessoa 91     33     8479  Rio de Janeiro
91  92  Pessoa 92     21     8393       São Paulo
95  96  Pessoa 96     22     8052       São Paulo

Banco com nova coluna 'Faixa Salarial':
   ID      Nome  Idade  Salário          Cidade Faixa Salarial
0   1  Pessoa 1     51     9739       São Paulo           Alta
1   2  Pessoa 2     51     7231  Rio de Janeiro          Média
2   3  Pessoa 3     26     3211  Rio de Janeiro          Baixa
3   4  Pessoa 4     21     9328  Rio de Janeiro           Alta
4   5  Pessoa 5     19     8588  Rio de Janeiro           Alta

Média salarial por cidade:
Cidade
Belo Horizonte    5973.470588
Curitiba          6203.900000
Rio de Janeiro    6591.520000
São Paulo         5904.657895
Name: Salário, dtype: float64

Banco expandido com novos registros:
      ID        Nome  Idade  Salário     Cidade Faixa Salarial
97    98   Pessoa 98     58     3080  São Paulo          Baixa
98    99   Pessoa 99     43     3493   Curitiba          Baixa
99   100  Pessoa 100     42     7211  São Paulo          Média
100  101  Pessoa 101     45     9500  Fortaleza            NaN
101  102  Pessoa 102     29     3000     Recife            NaN